### ISSUE TITLE
Inconsistent of the results for multiple tests

### ISSUE THREAD

**Issue by Licun1** [bogdanlab/RHOGE#2]
Hi, thank you for offering this software. But I encounted an issue. When I run this test multiple times. The results is inconsistent.
# Estimate rho_ge genome-wide for BMI and Triglyerides and approximate sample sizes
> ge_cor_res <- rhoge.gw(ANA_IDA, RA, 397378, 97173)
> head(ge_cor_res)
      RHOGE        SE    TSTAT DF          P
1 0.2889883 0.1325575 2.180097 68 0.03271528
> # Estimate rho_ge genome-wide for BMI and Triglyerides and approximate sample sizes
> ge_cor_res <- rhoge.gw(ANA_IDA, RA, 397378, 97173)
> head(ge_cor_res)
      RHOGE        SE    TSTAT DF         P
1 0.2316333 0.1658953 1.396262 68 0.1671771
> # Estimate rho_ge genome-wide for BMI and Triglyerides and approximate sample sizes
> ge_cor_res <- rhoge.gw(ANA_IDA, RA, 397378, 97173)
> head(ge_cor_res)
      RHOGE        SE    TSTAT DF         P
1 0.1976912 0.1446312 1.366864 68 0.1761701
> # Estimate rho_ge genome-wide for BMI and Triglyerides and approximate sample sizes
> ge_cor_res <- rhoge.gw(ANA_IDA, RA, 397378, 97173)
> head(ge_cor_res)
      RHOGE       SE    TSTAT DF         P
1 0.2350944 0.164506 1.429093 68 0.1575555
> # Estimate rho_ge genome-wide for BMI and Triglyerides and approximate sample sizes
> ge_cor_res <- rhoge.gw(ANA_IDA, RA, 397378, 97173)
> head(ge_cor_res)
      RHOGE        SE    TSTAT DF          P
1 0.2704979 0.1408241 1.920821 68 0.05894818  
I don't know why, could you help me?

**Comment by quattro** [comment]
Hi @Licun1 , there is a randomized component to deal with correlated features at local regions. This is why results may diff each time. Typically if results have enough signal, then the variation around the statistics should be minimal, but if there are outier signals, then you may see larger divergences across runs. 

One possible way to get a better sense of what a test statistic could be, is to run this many times, take the average TSTAT value, then compute a final p-value based on that average. Similarly, you could take the average effect, or plot the histogram of estimated effects.
